name: Build

on:
  workflow_dispatch: {}

env:
  applicationfolder: dist
  AWS_REGION: us-west-1
  S3BUCKET: cdk-workshop-webapp-deployment-bucket

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: chmod
        run: chmod -R +x ./.github

      - name: Build and Package Application
        id: package
        run: $GITHUB_WORKSPACE/.github/scripts/build.sh

      - name: Upload Artifact to s3
        run: |
          aws s3 cp dist/index.js s3://${{ env.S3BUCKET }}/dist/index.js

